[build-system]
build-backend = 'build_backend'
backend-path = ['.']
requires = ['meson-python', 'delvewheel; sys_platform == "win32"']

[project]
name = 'pfac'
description = 'Python bindings for the Flexible Atomic Code'
readme = 'README.md'
license = {file = 'LICENSE'}
dynamic = ['version']
dependencies = ['matplotlib', 'numpy']
